package com.freshkeep.app.activities

import android.content.Intent
import android.os.Bundle
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity
import androidx.credentials.Credential
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import androidx.credentials.exceptions.GetCredentialCancellationException
import androidx.credentials.exceptions.GetCredentialException
import androidx.credentials.exceptions.NoCredentialException
import androidx.lifecycle.lifecycleScope
import com.freshkeep.app.R
import com.freshkeep.app.databinding.ActivityLoginBinding
import com.freshkeep.app.db.SettingsDao
import com.freshkeep.app.views.Press
import com.google.android.libraries.identity.googleid.GetSignInWithGoogleOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.GoogleAuthProvider
import kotlinx.coroutines.launch

/**
 * Login.jsx — Continue with Google / Continue as Guest.
 * Google path: official Credential Manager "Sign in with Google" sheet →
 * Firebase Authentication (auth only — all app data stays in SQLite).
 * The signed-in account (email + display name) becomes the local session.
 */
class LoginActivity : AppCompatActivity() {

    private lateinit var binding: ActivityLoginBinding

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityLoginBinding.inflate(layoutInflater)
        setContentView(binding.root)

        Press.apply(binding.btnGoogle)
        Press.apply(binding.btnGuest)

        binding.btnGoogle.setOnClickListener { startGoogleSignIn() }
        binding.btnGuest.setOnClickListener {
            done(com.freshkeep.app.db.FreshKeepDbHelper.GUEST_UID, null, "guest", null, null)
        }
    }

    private fun startGoogleSignIn() {
        // default_web_client_id is generated by the google-services plugin from
        // app/google-services.json; looked up dynamically so the project also
        // compiles before that file has been added.
        val webClientIdRes = resources.getIdentifier("default_web_client_id", "string", packageName)
        if (webClientIdRes == 0) {
            Toast.makeText(
                this,
                getString(R.string.login_not_configured),
                Toast.LENGTH_LONG
            ).show()
            return
        }

        val request = GetCredentialRequest.Builder()
            .addCredentialOption(GetSignInWithGoogleOption.Builder(getString(webClientIdRes)).build())
            .build()

        lifecycleScope.launch {
            try {
                val result = CredentialManager.create(this@LoginActivity)
                    .getCredential(this@LoginActivity, request)
                handleCredential(result.credential)
            } catch (_: GetCredentialCancellationException) {
                // user dismissed the sheet — not an error
            } catch (_: NoCredentialException) {
                Toast.makeText(
                    this@LoginActivity,
                    getString(R.string.login_no_account),
                    Toast.LENGTH_LONG
                ).show()
            } catch (e: GetCredentialException) {
                Toast.makeText(
                    this@LoginActivity,
                    getString(R.string.error_signin_generic, e.message ?: e.type),
                    Toast.LENGTH_LONG
                ).show()
            }
        }
    }

    private fun handleCredential(credential: Credential) {
        if (credential is CustomCredential &&
            credential.type == GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL
        ) {
            val googleCred = GoogleIdTokenCredential.createFrom(credential.data)
            val firebaseCred = GoogleAuthProvider.getCredential(googleCred.idToken, null)
            FirebaseAuth.getInstance().signInWithCredential(firebaseCred)
                .addOnSuccessListener { result ->
                    val user = result.user
                    if (user == null) {
                        Toast.makeText(this, getString(R.string.error_signin_no_user), Toast.LENGTH_LONG).show()
                        return@addOnSuccessListener
                    }
                    // Firebase UID = the unique key every SQLite table is scoped by
                    done(
                        user.uid,
                        user.email ?: googleCred.id,
                        "google",
                        user.displayName ?: googleCred.displayName,
                        user.photoUrl?.toString(),
                    )
                }
                .addOnFailureListener { e ->
                    Toast.makeText(this, getString(R.string.error_signin_generic, e.message ?: ""), Toast.LENGTH_LONG).show()
                }
        } else {
            Toast.makeText(this, getString(R.string.error_credential_type), Toast.LENGTH_LONG).show()
        }
    }

    private fun done(uid: String, email: String?, authType: String, displayName: String?, photoUrl: String?) {
        val settings = SettingsDao(this)
        settings.login(uid, email, authType, displayName, photoUrl)

        // App.jsx fallback: if frequency was never set (returning guest), ask once.
        val next = if (settings.shopFrequency == null) {
            Intent(this, ShoppingSetupActivity::class.java)
        } else {
            // Entering Home resets the task so back can never reach Login again
            Intent(this, MainActivity::class.java)
                .addFlags(Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TASK)
        }
        startActivity(next)
        overridePendingTransition(R.anim.fade_in, R.anim.fade_out)
        finish()
    }
}
